version: "3"

services:
  
  #Reverse Proxy
  reverse-proxy:
    container_name: "reverse-proxy"
    image: "reverse-proxy"
    build : 
      context: "./"
      dockerfile: "reverse-proxy.dockerfile"
    depends_on:
      - "animals-go-ws"
    ports:
      - "80:80"

  #Authentication
  animals-go-auth:
    container_name: "animals-go-auth"
    image: "animals-go-auth"
    depends_on:
      - mongo
    build : 
      context: "../"
      dockerfile: "docker/animals-go-auth.dockerfile"
    environment:
      GIN_MODE: "release"
    ports:
      - "8001"

  #Web Service
  animals-go-ws:
    container_name: "animals-go-ws"
    image: "animals-go-ws"
    depends_on:
      - mongo
    build : 
      context: "../"
      dockerfile: "docker/animals-go-ws.dockerfile"
    environment:
      GIN_MODE: "release"
    ports:
      - "8002"

  #MongoDB
  mongo:
    container_name: "mongo"
    image: "mongo:latest"
    ports:
      - "27017"